// Maps the DMA export's Album column onto Parachoral releases and albums.
//
// Generated by `pnpm data:import <export.html> --scaffold`, then hand-corrected.
// Re-scaffolding preserves every value below but NOT your own comments, so keep
// notes to yourself somewhere else.
//
// Set an album's `releaseSlug` to null when its tracks span several releases, then
// re-scaffold: you'll get a `tracks` block listing every title in that album to
// resolve one by one. Anything still null is skipped by the import and reported.
//
// Albums already in /data:   destiny-ost, music-of-the-spheres
// Releases already in /data: 0_music-of-the-spheres, 1_d1-vanilla

/** Proposed additions to /data/releases.yaml. Merge them in by hand. */
export const releases = [
    { slug: "0_music-of-the-spheres", name: "Music of the Spheres", year: 2014, shorthand: "MOTS" },
    { slug: "1_d1-vanilla", name: "Destiny", year: 2014, shorthand: "DTY1" },
    { slug: "2_the-dark-below", name: "The Dark Below", year: 2014, shorthand: "TDBL" },
    { slug: "3_house-of-wolves", name: "House of Wolves", year: 2014, shorthand: "HWLV" },
    { slug: "4_the-taken-king", name: "The Taken King", year: 2015, shorthand: "ORYX" },
    { slug: "5_rise-of-iron", name: "Rise of Iron", year: 2016, shorthand: "SIVA" },
    { slug: "the-dawning", name: "The Dawning", year: 2016, shorthand: "TD__" }, // TODO: ordinal prefix, name, shorthand
    { slug: "destiny-2", name: "Destiny 2", year: 2017, shorthand: "DTY2" }, // TODO: ordinal prefix, name, shorthand
    { slug: "curse-of-osiris-warmind", name: "Curse of Osiris/Warmind", year: 2018, shorthand: "COOW" }, // TODO: ordinal prefix, name, shorthand
    { slug: "forsaken", name: "Forsaken", year: 2018, shorthand: "FORS" }, // TODO: ordinal prefix, name, shorthand
    { slug: "whisper-of-the-worm", name: "Whisper of the Worm", year: 2018, shorthand: "WOTW" }, // TODO: ordinal prefix, name, shorthand
    { slug: "forsaken-annual-pass", name: "Forsaken Annual Pass", year: 2019, shorthand: "FAP_" }, // TODO: ordinal prefix, name, shorthand
    { slug: "shadowkeep", name: "Shadowkeep", year: 2019, shorthand: "SHKP" }, // TODO: ordinal prefix, name, shorthand
    { slug: "beyond-light", name: "Beyond Light", year: 2020, shorthand: "BNDL" }, // TODO: ordinal prefix, name, shorthand
    { slug: "solstice-of-heroes-2020", name: "Solstice of Heroes (2020)", year: 2020, shorthand: "SOH2" }, // TODO: ordinal prefix, name, shorthand
    { slug: "the-prophecy-dungeon", name: "The Prophecy Dungeon", year: 2020, shorthand: "TPD_" }, // TODO: ordinal prefix, name, shorthand
    { slug: "grasp-of-avarice", name: "Grasp of Avarice", year: 2021, shorthand: "GOA_" }, // TODO: ordinal prefix, name, shorthand
    { slug: "season-of-the-splicer", name: "Season of the Splicer", year: 2021, shorthand: "SOTS" }, // TODO: ordinal prefix, name, shorthand
    { slug: "season-of-plunder", name: "Season of Plunder", year: 2022, shorthand: "SOP_" }, // TODO: ordinal prefix, name, shorthand
    { slug: "the-witch-queen", name: "The Witch Queen", year: 2022, shorthand: "TWQ_" }, // TODO: ordinal prefix, name, shorthand
    { slug: "lightfall", name: "Lightfall", year: 2023, shorthand: "LIGH" }, // TODO: ordinal prefix, name, shorthand
    { slug: "the-final-shape", name: "The Final Shape", year: 2024, shorthand: "TFS_" }, // TODO: ordinal prefix, name, shorthand
    { slug: "legacy-of-the-past", name: "Legacy of the Past", year: 2025, shorthand: "LOTP" }, // TODO: ordinal prefix, name, shorthand
    { slug: "renegades", name: "Renegades", year: 2025, shorthand: "RENE" }, // TODO: ordinal prefix, name, shorthand
    { slug: "the-edge-of-fate", name: "The Edge of Fate", year: 2025, shorthand: "TEOF" }, // TODO: ordinal prefix, name, shorthand
    { slug: "rising", name: "Rising", year: 2025, shorthand: "RISI" }, // TODO: ordinal prefix, name, shorthand
    { slug: "monument-of-triumph", name: "Monument of Triumph", year: 2026, shorthand: "MOT_" }, // TODO: ordinal prefix, name, shorthand
];

export const albums = {
    "Music of the Spheres": {
        albumSlug: "music-of-the-spheres",
        releaseSlug: "0_music-of-the-spheres",
    },
    "Destiny": {
        albumSlug: "destiny-ost",
        releaseSlug: "1_d1-vanilla",
        releasedAt: "2014-09-26",
    },
    "Destiny: The Taken King": {
        albumSlug: "the-taken-king",
        releaseSlug: "4_the-taken-king",
        releasedAt: "2015-09-15",
    },
    "Destiny: Rise of Iron": {
        albumSlug: "rise-of-iron",
        releaseSlug: "5_rise-of-iron",
        releasedAt: "2016-09-16",
    },
    "The Dawning": {
        albumSlug: "the-dawning",
        releaseSlug: "the-dawning", // TODO: confirm
        releasedAt: "2016-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2": {
        albumSlug: "destiny-2",
        releaseSlug: "destiny-2", // TODO: confirm
        releasedAt: "2017-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: Curse of Osiris/Warmind": {
        albumSlug: "destiny-2-curse-of-osiris-warmind",
        releaseSlug: null, // TODO: spans releases — resolve per track below
        releasedAt: "2018-01-01", // TODO: real date, export only gives Year
        tracks: {
            "a-god-on-mars": null, // TODO
            "a-guardians-past": null, // TODO
            "a-traitor-to-the-empire": null, // TODO
            "all-the-time-in-the-world": null, // TODO
            "beneath-the-ice": null, // TODO
            "convergence-part-1": null, // TODO
            "convergence-part-2": null, // TODO
            "eater-of-worlds": null, // TODO
            "fields-of-glass": null, // TODO
            "garden-world": null, // TODO
            "hellas-basin": null, // TODO
            "hive-extermination": null, // TODO
            "mercurys-golden-age": null, // TODO
            "nokris": null, // TODO
            "out-of-time": null, // TODO
            "silence-and-shadow": null, // TODO
            "the-frozen-horde": null, // TODO
            "the-wake": null, // TODO
            "tree-of-probabilities": null, // TODO
            "valkyrie": null, // TODO
            "warmind": null, // TODO
        },
    },
    "Destiny 2: Forsaken": {
        albumSlug: "destiny-2-forsaken",
        releaseSlug: "forsaken", // TODO: confirm
        releasedAt: "2018-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: Whisper of the Worm": {
        albumSlug: "destiny-2-whisper-of-the-worm",
        releaseSlug: "whisper-of-the-worm", // TODO: confirm
        releasedAt: "2018-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: Forsaken Annual Pass": {
        albumSlug: "destiny-2-forsaken-annual-pass",
        releaseSlug: "forsaken-annual-pass", // TODO: confirm
        releasedAt: "2019-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: Shadowkeep": {
        albumSlug: "destiny-2-shadowkeep",
        releaseSlug: "shadowkeep", // TODO: confirm
        releasedAt: "2019-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: Beyond Light": {
        albumSlug: "destiny-2-beyond-light",
        releaseSlug: "beyond-light", // TODO: confirm
        releasedAt: "2020-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: Solstice of Heroes (2020)": {
        albumSlug: "destiny-2-solstice-of-heroes-2020",
        releaseSlug: "solstice-of-heroes-2020", // TODO: confirm
        releasedAt: "2020-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: The Prophecy Dungeon": {
        albumSlug: "destiny-2-the-prophecy-dungeon",
        releaseSlug: "the-prophecy-dungeon", // TODO: confirm
        releasedAt: "2020-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: Grasp of Avarice": {
        albumSlug: "destiny-2-grasp-of-avarice",
        releaseSlug: "grasp-of-avarice", // TODO: confirm
        releasedAt: "2021-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: Season of the Splicer": {
        albumSlug: "destiny-2-season-of-the-splicer",
        releaseSlug: "season-of-the-splicer", // TODO: confirm
        releasedAt: "2021-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: Season of Plunder": {
        albumSlug: "destiny-2-season-of-plunder",
        releaseSlug: "season-of-plunder", // TODO: confirm
        releasedAt: "2022-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: The Witch Queen": {
        albumSlug: "destiny-2-the-witch-queen",
        releaseSlug: "the-witch-queen", // TODO: confirm
        releasedAt: "2022-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: Lightfall": {
        albumSlug: "destiny-2-lightfall",
        releaseSlug: "lightfall", // TODO: confirm
        releasedAt: "2023-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: The Final Shape": {
        albumSlug: "destiny-2-the-final-shape",
        releaseSlug: "the-final-shape", // TODO: confirm
        releasedAt: "2024-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: Legacy of the Past": {
        albumSlug: "destiny-2-legacy-of-the-past",
        releaseSlug: "legacy-of-the-past", // TODO: confirm
        releasedAt: "2025-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: Renegades": {
        albumSlug: "destiny-2-renegades",
        releaseSlug: "renegades", // TODO: confirm
        releasedAt: "2025-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: The Edge of Fate": {
        albumSlug: "destiny-2-the-edge-of-fate",
        releaseSlug: "the-edge-of-fate", // TODO: confirm
        releasedAt: "2025-01-01", // TODO: real date, export only gives Year
    },
    "Destiny: Rising": {
        albumSlug: "destiny-rising",
        releaseSlug: "rising", // TODO: confirm
        releasedAt: "2025-01-01", // TODO: real date, export only gives Year
    },
    "Destiny 2: Monument of Triumph": {
        albumSlug: "destiny-2-monument-of-triumph",
        releaseSlug: "monument-of-triumph", // TODO: confirm
        releasedAt: "2026-01-01", // TODO: real date, export only gives Year
    }, "Destiny 2: Curse of Osiris/Warmind": {
        albumSlug: "curse-of-osiris-warmind",
        releaseSlug: "monument-of-triumph", // TODO: confirm
        releasedAt: "2026-01-01", // TODO: real date, export only gives Year
    },
};
