/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as MotifsRouteImport } from './routes/motifs'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTracksRouteImport } from './routes/_layout/tracks'
import { Route as TrackTrackSlugRouteImport } from './routes/track/$trackSlug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const MotifsRoute = MotifsRouteImport.update({
  id: '/motifs',
  path: '/motifs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTracksRoute = LayoutTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => LayoutRoute,
} as any)
const TrackTrackSlugRoute = TrackTrackSlugRouteImport.update({
  id: '/track/$trackSlug',
  path: '/track/$trackSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof AboutRoute
  '/albums': typeof AlbumsRoute
  '/motifs': typeof MotifsRoute
  '/releases': typeof ReleasesRoute
  '/tracks': typeof LayoutTracksRoute
  '/track/$trackSlug': typeof TrackTrackSlugRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/albums': typeof AlbumsRoute
  '/motifs': typeof MotifsRoute
  '/releases': typeof ReleasesRoute
  '/tracks': typeof LayoutTracksRoute
  '/track/$trackSlug': typeof TrackTrackSlugRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/albums': typeof AlbumsRoute
  '/motifs': typeof MotifsRoute
  '/releases': typeof ReleasesRoute
  '/_layout/tracks': typeof LayoutTracksRoute
  '/track/$trackSlug': typeof TrackTrackSlugRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/albums'
    | '/motifs'
    | '/releases'
    | '/tracks'
    | '/track/$trackSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/albums'
    | '/motifs'
    | '/releases'
    | '/tracks'
    | '/track/$trackSlug'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/about'
    | '/albums'
    | '/motifs'
    | '/releases'
    | '/_layout/tracks'
    | '/track/$trackSlug'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  AlbumsRoute: typeof AlbumsRoute
  MotifsRoute: typeof MotifsRoute
  ReleasesRoute: typeof ReleasesRoute
  TrackTrackSlugRoute: typeof TrackTrackSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motifs': {
      id: '/motifs'
      path: '/motifs'
      fullPath: '/motifs'
      preLoaderRoute: typeof MotifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tracks': {
      id: '/_layout/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof LayoutTracksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/track/$trackSlug': {
      id: '/track/$trackSlug'
      path: '/track/$trackSlug'
      fullPath: '/track/$trackSlug'
      preLoaderRoute: typeof TrackTrackSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutTracksRoute: typeof LayoutTracksRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutTracksRoute: LayoutTracksRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  AlbumsRoute: AlbumsRoute,
  MotifsRoute: MotifsRoute,
  ReleasesRoute: ReleasesRoute,
  TrackTrackSlugRoute: TrackTrackSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
