/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutActivitiesRouteImport } from './routes/_layout/activities'
import { Route as LayoutAlbumsRouteImport } from './routes/_layout/albums'
import { Route as LayoutMotifsRouteImport } from './routes/_layout/motifs'
import { Route as LayoutReleasesRouteImport } from './routes/_layout/releases'
import { Route as LayoutTracksRouteImport } from './routes/_layout/tracks'
import { Route as LayoutActivityActivitySlugRouteImport } from './routes/_layout/activity/$activitySlug'
import { Route as LayoutMotifMotifSlugRouteImport } from './routes/_layout/motif/$motifSlug'
import { Route as LayoutTrackTrackSlugRouteImport } from './routes/_layout/track/$trackSlug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutActivitiesRoute = LayoutActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAlbumsRoute = LayoutAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMotifsRoute = LayoutMotifsRouteImport.update({
  id: '/motifs',
  path: '/motifs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReleasesRoute = LayoutReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTracksRoute = LayoutTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutActivityActivitySlugRoute =
  LayoutActivityActivitySlugRouteImport.update({
    id: '/activity/$activitySlug',
    path: '/activity/$activitySlug',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutMotifMotifSlugRoute = LayoutMotifMotifSlugRouteImport.update({
  id: '/motif/$motifSlug',
  path: '/motif/$motifSlug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTrackTrackSlugRoute = LayoutTrackTrackSlugRouteImport.update({
  id: '/track/$trackSlug',
  path: '/track/$trackSlug',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/activities': typeof LayoutActivitiesRoute
  '/albums': typeof LayoutAlbumsRoute
  '/motifs': typeof LayoutMotifsRoute
  '/releases': typeof LayoutReleasesRoute
  '/tracks': typeof LayoutTracksRoute
  '/activity/$activitySlug': typeof LayoutActivityActivitySlugRoute
  '/motif/$motifSlug': typeof LayoutMotifMotifSlugRoute
  '/track/$trackSlug': typeof LayoutTrackTrackSlugRoute
}
export interface FileRoutesByTo {
  '/about': typeof LayoutAboutRoute
  '/activities': typeof LayoutActivitiesRoute
  '/albums': typeof LayoutAlbumsRoute
  '/motifs': typeof LayoutMotifsRoute
  '/releases': typeof LayoutReleasesRoute
  '/tracks': typeof LayoutTracksRoute
  '/': typeof LayoutIndexRoute
  '/activity/$activitySlug': typeof LayoutActivityActivitySlugRoute
  '/motif/$motifSlug': typeof LayoutMotifMotifSlugRoute
  '/track/$trackSlug': typeof LayoutTrackTrackSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/activities': typeof LayoutActivitiesRoute
  '/_layout/albums': typeof LayoutAlbumsRoute
  '/_layout/motifs': typeof LayoutMotifsRoute
  '/_layout/releases': typeof LayoutReleasesRoute
  '/_layout/tracks': typeof LayoutTracksRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/activity/$activitySlug': typeof LayoutActivityActivitySlugRoute
  '/_layout/motif/$motifSlug': typeof LayoutMotifMotifSlugRoute
  '/_layout/track/$trackSlug': typeof LayoutTrackTrackSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/albums'
    | '/motifs'
    | '/releases'
    | '/tracks'
    | '/activity/$activitySlug'
    | '/motif/$motifSlug'
    | '/track/$trackSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/activities'
    | '/albums'
    | '/motifs'
    | '/releases'
    | '/tracks'
    | '/'
    | '/activity/$activitySlug'
    | '/motif/$motifSlug'
    | '/track/$trackSlug'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/about'
    | '/_layout/activities'
    | '/_layout/albums'
    | '/_layout/motifs'
    | '/_layout/releases'
    | '/_layout/tracks'
    | '/_layout/'
    | '/_layout/activity/$activitySlug'
    | '/_layout/motif/$motifSlug'
    | '/_layout/track/$trackSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/activities': {
      id: '/_layout/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof LayoutActivitiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/albums': {
      id: '/_layout/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof LayoutAlbumsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/motifs': {
      id: '/_layout/motifs'
      path: '/motifs'
      fullPath: '/motifs'
      preLoaderRoute: typeof LayoutMotifsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/releases': {
      id: '/_layout/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof LayoutReleasesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tracks': {
      id: '/_layout/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof LayoutTracksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/activity/$activitySlug': {
      id: '/_layout/activity/$activitySlug'
      path: '/activity/$activitySlug'
      fullPath: '/activity/$activitySlug'
      preLoaderRoute: typeof LayoutActivityActivitySlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/motif/$motifSlug': {
      id: '/_layout/motif/$motifSlug'
      path: '/motif/$motifSlug'
      fullPath: '/motif/$motifSlug'
      preLoaderRoute: typeof LayoutMotifMotifSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/track/$trackSlug': {
      id: '/_layout/track/$trackSlug'
      path: '/track/$trackSlug'
      fullPath: '/track/$trackSlug'
      preLoaderRoute: typeof LayoutTrackTrackSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutActivitiesRoute: typeof LayoutActivitiesRoute
  LayoutAlbumsRoute: typeof LayoutAlbumsRoute
  LayoutMotifsRoute: typeof LayoutMotifsRoute
  LayoutReleasesRoute: typeof LayoutReleasesRoute
  LayoutTracksRoute: typeof LayoutTracksRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutActivityActivitySlugRoute: typeof LayoutActivityActivitySlugRoute
  LayoutMotifMotifSlugRoute: typeof LayoutMotifMotifSlugRoute
  LayoutTrackTrackSlugRoute: typeof LayoutTrackTrackSlugRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutActivitiesRoute: LayoutActivitiesRoute,
  LayoutAlbumsRoute: LayoutAlbumsRoute,
  LayoutMotifsRoute: LayoutMotifsRoute,
  LayoutReleasesRoute: LayoutReleasesRoute,
  LayoutTracksRoute: LayoutTracksRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutActivityActivitySlugRoute: LayoutActivityActivitySlugRoute,
  LayoutMotifMotifSlugRoute: LayoutMotifMotifSlugRoute,
  LayoutTrackTrackSlugRoute: LayoutTrackTrackSlugRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
